python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-linear-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-linear-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-linear-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-linear-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-linear-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-linear-2c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-rbf-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-rbf-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-rbf-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-rbf-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-rbf-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-rbf-2c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-tanimoto-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-tanimoto-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-tanimoto-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-tanimoto-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-tanimoto-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Ab-oct-SVM-tanimoto-2c.cfg

python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-linear-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-linear-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-linear-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-linear-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-linear-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-linear-2c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-rbf-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-rbf-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-rbf-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-rbf-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-rbf-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-rbf-2c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-tanimoto-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-tanimoto-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-tanimoto-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-tanimoto-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-tanimoto-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/De-aq-SVM-tanimoto-2c.cfg

python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-linear-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-linear-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-linear-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-linear-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-linear-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-linear-2c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-rbf-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-rbf-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-rbf-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-rbf-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-rbf-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-rbf-2c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-tanimoto-a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-tanimoto-b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-tanimoto-c.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-tanimoto-2a.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-tanimoto-2b.cfg
python conv_qsar/main/svm_cv.py conv_qsar/inputs/SVM_baselines/Br-tm-SVM-tanimoto-2c.cfg